kind: pipeline
name: default

steps:
- name: test and build
  image: golang
  commands:
  - go get github.com/cuttle-ai/web-starter && cd $GOPATH/src/github.com/cuttle-ai/web-starter && go get ./...
  - go test -coverprofile=coverage.out ./... && cp coverage.out /drone/src/
  - GOOS=linux GOARCH=amd64 go build -o web-starter && mkdir /drone/src/dist && cp web-starter /drone/src/dist/
  - GOOS=darwin GOARCH=amd64 go build -o web-starter.cmd && cp web-starter.cmd /drone/src/dist/

- name: codacy
  image: plugins/codacy
  settings:
    token:
      from_secret: codacy-api-token

- name: release
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github-api-token
    files: dist/*
  when:
    event: tag