kind: pipeline
name: default

steps:
- name: test and build
  image: golang
  commands:
  - go get github.com/cuttle-ai/web-starter && cd $GOPATH/src/github.com/cuttle-ai/web-starter && go get ./...
  - go test -coverprofile=coverage.out ./...
  - GOOS=linux GOARCH=amd64 go build -o dist/web-starter
  - GOOS=darwin GOARCH=amd64 go build -o dist/web-starter.cmd

- name: codacy
  image: plugins/codacy
  settings:
    token:
      from_secret: codacy-api-token
  commands:
    - cd $GOPATH/src/github.com/cuttle-ai/web-starter

- name: release
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github-api-token
    files: dist/*
  commands:
    - cd $GOPATH/src/github.com/cuttle-ai/web-starter
  when:
    event: tag