kind: pipeline
name: default

steps:
- name: build and test
  image: golang
  commands:
  - go get github.com/cuttle-ai/web-starter && cd $GOPATH/src/github.com/cuttle-ai/web-starter && go get ./...
  - go build ./...
  - go test ./...
