kind: pipeline
name: default

steps:
- name: test and build
  image: golang
  commands:
  - pwd
  - go get github.com/cuttle-ai/web-starter && cd $GOPATH/src/github.com/cuttle-ai/web-starter && go get ./...
  - go test -coverprofile=/drone/dist/coverage.out ./...
  - GOOS=linux GOARCH=amd64 go build -o /drone/dist/web-starter
  - GOOS=darwin GOARCH=amd64 go build -o /drone/dist/web-starter.cmd

- name: codacy
  image: plugins/codacy
  settings:
    token:
      from_secret: codacy-api-token

- name: release
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github-api-token
    files: dist/*
  when:
    event: tag